# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uploads_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import icons_pb2 as icons__pb2
import attachments_pb2 as attachments__pb2
import moderation_pb2 as moderation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15uploads_service.proto\x12\x07uploads\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0bicons.proto\x1a\x11\x61ttachments.proto\x1a\x10moderation.proto2\xdc\x02\n\x07Uploads\x12=\n\nUploadIcon\x12\x16.uploads.UploadIconReq\x1a\x17.uploads.UploadIconResp\x12L\n\x0f\x43laimAttachment\x12\x1b.uploads.ClaimAttachmentReq\x1a\x1c.uploads.ClaimAttachmentResp\x12H\n\x10\x44\x65leteAttachment\x12\x1c.uploads.DeleteAttachmentReq\x1a\x16.google.protobuf.Empty\x12:\n\tBlockFile\x12\x15.uploads.BlockFileReq\x1a\x16.google.protobuf.Empty\x12>\n\x0bUnblockFile\x12\x17.uploads.UnblockFileReq\x1a\x16.google.protobuf.EmptyB\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uploads_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_UPLOADS']._serialized_start=114
  _globals['_UPLOADS']._serialized_end=462
# @@protoc_insertion_point(module_scope)
